import { Platform, StyleSheet } from 'react-native';

import { Fonts } from '@/constants/theme';

export const styles = StyleSheet.create({
  screen: { flex: 1 },
  header: { elevation: 0 },
  headerMain: { flex: 1, minWidth: 0, alignSelf: 'stretch', justifyContent: 'center' },
  headerActions: { flexDirection: 'row', alignItems: 'center', flexShrink: 0 },
  headerTitle: { fontFamily: Fonts.display, fontWeight: '700' },
  headerSessionAnchor: { flex: 1, alignSelf: 'stretch', justifyContent: 'center', borderRadius: 14, marginRight: 8 },
  headerSessionAnchorPressed: { opacity: 0.82 },
  headerSessionContent: { flexDirection: 'row', alignItems: 'center', gap: 8, minWidth: 0, minHeight: 48, paddingRight: 4 },
  headerSessionTextWrap: { flex: 1, minWidth: 0 },
  headerUsage: { fontFamily: Fonts.sans, fontSize: 11, marginTop: 1 },
  sessionPickerOverlay: { ...StyleSheet.absoluteFillObject },
  sessionPickerBackdrop: { ...StyleSheet.absoluteFillObject },
  sessionPickerBackdropFill: { flex: 1, backgroundColor: 'rgba(0,0,0,0.28)' },
  sessionPickerSheet: { position: 'absolute', left: 0, right: 0, bottom: 0, borderTopLeftRadius: 24, borderTopRightRadius: 24, borderWidth: 1, overflow: 'hidden' },
  sessionPickerHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1 },
  sessionPickerCloseButton: { minHeight: 36, justifyContent: 'center', paddingHorizontal: 10, borderRadius: 999 },
  sessionPickerCloseButtonPressed: { opacity: 0.82 },
  sessionPickerCloseLabel: { fontFamily: Fonts.sans, fontSize: 15, fontWeight: '600' },
  sessionPickerList: { padding: 12, gap: 8, paddingBottom: 24 },
  sessionPickerItem: { borderRadius: 16, borderWidth: 1 },
  sessionPickerItemRow: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 56, paddingHorizontal: 14, paddingVertical: 12 },
  sessionPickerItemIcon: { width: 32, height: 32, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  sessionPickerItemTextWrap: { flex: 1, gap: 2 },
  sessionPickerItemTitle: { fontFamily: Fonts.sans, fontSize: 16 },
  sessionPickerItemSubtitle: { fontFamily: Fonts.sans, fontSize: 13 },
  usageProvider: { borderWidth: 1, borderRadius: 14, gap: 8, padding: 12 },
  usageModel: { gap: 4, paddingLeft: 8 },
  usageRow: { alignItems: 'center', flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
  contextProgress: { borderRadius: 999, height: 8 },
  tabsRow: { flexDirection: 'row', borderBottomWidth: 1 },
  chatArea: { flex: 1, position: 'relative' },
  scroll: { flex: 1 },
  content: { padding: 12, gap: 12, paddingBottom: 20 },
  transcriptItem: { marginBottom: 12 },
  transcriptFooter: { gap: 12 },
  noticeCard: { borderRadius: 20 },
  waitingNoticeContent: { gap: 8 },
  waitingNoticeHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  emptyCard: { borderRadius: 22 },
  emptyContent: { gap: 14 },
  emptyTitle: { fontFamily: Fonts.display, fontWeight: '700' },
  promptStack: { gap: 10 },
  promptCard: { borderWidth: 1, borderRadius: 18 },
  promptCardInner: { flexDirection: 'row', gap: 12, alignItems: 'center', padding: 14 },
  sectionStack: { gap: 12 },
  sectionCard: { borderRadius: 18 },
  sectionHeaderCard: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, alignItems: 'center' },
  paginationRow: { alignItems: 'center', paddingVertical: 4 },
  loadingRow: { flexDirection: 'row', gap: 10, alignItems: 'center', paddingHorizontal: 8, paddingBottom: 8 },
  composer: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: Platform.select({ ios: 24, default: 12 }),
    gap: 10,
    borderTopWidth: 1,
  },
  composerDockRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  inputShell: { borderWidth: 1, borderRadius: 22, paddingLeft: 12, paddingRight: 6, paddingTop: 0, paddingBottom: 0, minHeight: 48, justifyContent: 'center' },
  inputShellFlex: { flex: 1 },
  // Row containing the input and inline icon. Center children by default so the
  // input visually floats vertically when single-line.
  composerRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  // Keep input flexible but start very compact
  // Input text area: keep the text container small; inner padding provides the 4px top/bottom
  // Keep text vertically centered by default; multiline growth still allowed.
  input: { flex: 1, minHeight: 24, maxHeight: 120, fontSize: 17, lineHeight: 22, marginHorizontal: -4, paddingVertical: 0, textAlignVertical: 'center' },
  inputContentCompact: { paddingHorizontal: 0, paddingTop: 0, paddingBottom: 0, fontFamily: Fonts.sans },
  controlsRow: { flexDirection: 'row', flexWrap: 'nowrap', gap: 6, paddingHorizontal: 0, alignItems: 'center', width: '100%' },
  attachmentRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, paddingHorizontal: 2 },
  attachmentChip: { maxWidth: '100%', minHeight: 40, flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', borderRadius: 20, paddingLeft: 12 },
  attachmentLabel: { flexShrink: 1 },
  attachmentRemoveButton: { width: 40, height: 40, margin: 0 },
  conversationBanner: { borderWidth: 1, borderRadius: 18, paddingHorizontal: 14, paddingVertical: 12, gap: 8 },
  conversationBannerHeader: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, alignItems: 'center' },
  voiceStatusRow: { paddingHorizontal: 2 },
  voiceStatusChip: { alignSelf: 'flex-start' },
  composerVoiceButton: { margin: 0, alignSelf: 'center' },
  composerPrimaryButton: { margin: 0, width: 44, height: 44, borderRadius: 999, alignSelf: 'center' },
  composerActionButton: { margin: 0 },
  sendErrorCard: { marginHorizontal: 12, marginBottom: 12, borderRadius: 16 },
  sendErrorContent: { gap: 8 },
  sendErrorActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 4 },
  diffListCardContent: { paddingHorizontal: 0, paddingVertical: 0 },
  todoOverlay: { position: 'absolute', left: 12, right: 12, bottom: 12, zIndex: 2, borderRadius: 16, borderWidth: 1, overflow: 'hidden' },
  todoHeader: { minHeight: 48, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 4 },
  todoSummary: { flex: 1 },
  todoToggleButton: { width: 40, height: 40, margin: 0 },
  todoListScroll: { maxHeight: 240 },
  todoList: { gap: 4, paddingHorizontal: 16, paddingBottom: 12 },
  todoItemRow: { flexDirection: 'row', alignItems: 'center', gap: 4, minHeight: 40 },
  todoStatusIcon: { margin: 0 },
  todoTextWrap: { flex: 1 },
  keyboardDismissRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', paddingVertical: 4, borderTopWidth: 1 },
  keyboardDismissButton: { minHeight: 32 },
});
